apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-working
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-working
  template:
    metadata:
      labels:
        app: nginx-working
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app.name
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app.environment
