apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-simple
  template:
    metadata:
      labels:
        app: nginx-simple
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
