apiVersion: v1
kind: Pod
metadata:
  name: security-advanced
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - name: nginx-secure
    image: nginxinc/nginx-unprivileged:alpine
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE  # 允许绑定特权端口
    ports:
    - containerPort: 80     # 现在可以绑定80端口
