version: '3.8'
services:
  web-server:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - app-network
      
  python-app:
    image: python:3.9-alpine
    command: python -m http.server 8000
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
