services:
  # 模型推理服务
  model-service:
    image: python:3.9-alpine
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./model-service:/app
    networks:
      - mlops-network

  # 数据库服务
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: mlops
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mlops123
    ports:
      - "5432:5432"
    networks:
      - mlops-network

  # 缓存服务
  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mlops-network

  # 监控服务
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge
