apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod-2
spec:
  containers:
  - name: test-container-2
    image: nginx:alpine
    volumeMounts:
    - name: pvc-storage
      mountPath: /shared-data
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: my-first-pvc
